-- MySQL Script generated by MySQL Workbench
-- Tue Apr 24 11:05:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `NASCIMENTO` DATE NOT NULL,
  `RG` VARCHAR(20) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `TELEFONE` VARCHAR(11) NOT NULL,
  `SENHA` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`ID_CLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FUNCIONARIO` (
  `ID_FUNCIONARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `RG` VARCHAR(20) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `SENHA` VARCHAR(16) NOT NULL,
  `SETOR` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_FUNCIONARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTO` (
  `ID_PRODUTO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(100) NOT NULL,
  `PRECO` DOUBLE NOT NULL,
  `VALIDADE` DATE NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  PRIMARY KEY (`ID_PRODUTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `ID_PEDIDO` INT NOT NULL AUTO_INCREMENT,
  `CLIENTE_ID_CLIENTE` INT NOT NULL,
  `DATA` DATE NOT NULL,
  `MESA` INT NOT NULL,
  PRIMARY KEY (`ID_PEDIDO`, `CLIENTE_ID_CLIENTE`),
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_ID_CLIENTE` ASC),
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID_CLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEM_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITEM_CLIENTE` (
  `ID_ITEM_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `PRODUTO_ID_PRODUTO` INT NOT NULL,
  `PEDIDO_ID_PEDIDO` INT NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  PRIMARY KEY (`ID_ITEM_CLIENTE`, `PRODUTO_ID_PRODUTO`, `PEDIDO_ID_PEDIDO`),
  INDEX `fk_ITEM_PEDIDO_PRODUTO1_idx` (`PRODUTO_ID_PRODUTO` ASC),
  INDEX `fk_ITEM_CLIENTE_PEDIDO1_idx` (`PEDIDO_ID_PEDIDO` ASC),
  CONSTRAINT `fk_ITEM_PEDIDO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_ID_PRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`ID_PRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_CLIENTE_PEDIDO1`
    FOREIGN KEY (`PEDIDO_ID_PEDIDO`)
    REFERENCES `mydb`.`PEDIDO` (`ID_PEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
