CREATE TABLE IF NOT EXISTS DOADOR
(    
    IDENTIFICADOR INT NOT NULL AUTO_INCREMENT,     
    NOME  VARCHAR(200) NOT NULL,    
    NASCIMENTO DATE NOT NULL,    
    SEXO VARCHAR(1) NOT NULL,     
    NOME_PAI VARCHAR(200) NOT NULL ,    
    NOME_MAE VARCHAR(200) NOT NULL ,     
    RG VARCHAR(20) NOT NULL ,     
    ENDERECO VARCHAR(100) NOT NULL ,   
    CEP VARCHAR(9) NOT NULL ,     
    ESTADO VARCHAR(2) NOT NULL ,     
    CIDADE VARCHAR(100) NOT NULL, 
    BAIRRO VARCHAR(200) NOT NULL, 
    TELEFONE VARCHAR(11) NOT NULL,
    PRIMARY KEY (IDENTIFICADOR)
);

CREATE TABLE IF NOT EXISTS DOACAO
(    
    IDENTIFICADOR INT NOT NULL AUTO_INCREMENT,   
    DATA_DOACAO DATE NOT NULL,     
    ID_DOADOR  INT NOT NULL,    
    HepatiteB BOOLEAN  NULL,     
    HepatiteC BOOLEAN  NULL,  
    DoencaChagas BOOLEAN  NULL,  
    Sifilis BOOLEAN  NULL,  
    Aids BOOLEAN  NULL,  
    HTLVI BOOLEAN  NULL,  
    HTLVII BOOLEAN  NULL,  
    AnticorposIrregulares BOOLEAN  NULL,  
    TipoSangue VARCHAR(2)  NULL ,  
    RhSangue BOOLEAN  NULL ,
    Anemia BOOLEAN  NULL ,
    Triagem BOOLEAN  NULL ,
    PRIMARY KEY (IDENTIFICADOR)
);